In [130]:
import pandas as pd

In [131]:
dados = pd.read_csv('/content/Customer-Churn.csv')

In [132]:
dados.shape

(7043, 18)

In [133]:
dados.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [134]:
traducao_dic = {'Sim': 1,
                'Nao': 0}

dadosmodificados = dados[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(traducao_dic)
dadosmodificados.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [136]:
#transformação pelo get_dummies
dummie_dados = pd.get_dummies(dados.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'],
                axis=1))

#junção dos dados trasformados com os que já tinhamos
dados_final = pd.concat([dadosmodificados, dummie_dados], axis=1)

In [137]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                        False   
1               34        56.95                         True   
2                2        53.85                         True   
3               45        42.30                        False   
4                2        70.70                         True   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                          True                        False   
1                                         False                        False   
2                                         False                        False   
3                                          True                        False   
4                                         False                        False   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                   True                          False   
1                   True                          False   
2                   True                          False   
3                   True                          False   
4                  False                           True   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  \
0                  False                 True   
1                  False                False   
2                  False                False   
3                  False                False   
4                  False                 True   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim  \
0                                 False                False   
1                                 False                 True   
2                                 False                 True   
3                                 False                 True   
4                                 False                False   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim  \
0             False                              False              True   
1              True                              False             False   
2             False                              False              True   
3              True                              False             False   
4              True                              False             False   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet  \
0                     True                                     False   
1                    False                                     False   
2                     True                                     False   
3                    False                                     False   
4                     True                                     False   

   SeguroNoDispositivo_Sim  SuporteTecnico_Nao  \
0                    False                True   
1                     True                True   
2                    False                True   
3                     True               False   
4                    False                True   

   SuporteTecnico_SemServicoDeInternet  SuporteTecnico_Sim  TVaCabo_Nao  \
0                                False               False         True   
1                                False               False         True   
2                                False               False         True   
3                                False                True         True   
4                                False               False         

In [138]:
pd.set_option('display.max_columns', 39)

In [139]:
dados_final.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                        False   
1               34        56.95                         True   
2                2        53.85                         True   
3               45        42.30                        False   
4                2        70.70                         True   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                          True                        False   
1                                         False                        False   
2                                         False                        False   
3                                          True                        False   
4                                         False                        False   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                   True                          False   
1                   True                          False   
2                   True                          False   
3                   True                          False   
4                  False                           True   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  \
0                  False                 True   
1                  False                False   
2                  False                False   
3                  False                False   
4                  False                 True   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim  \
0                                 False                False   
1                                 False                 True   
2                                 False                 True   
3                                 False                 True   
4                                 False                False   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim  \
0             False                              False              True   
1              True                              False             False   
2             False                              False              True   
3              True                              False             False   
4              True                              False             False   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet  \
0                     True                                     False   
1                    False                                     False   
2                     True                                     False   
3                    False                                     False   
4                     True                                     False   

   SeguroNoDispositivo_Sim  SuporteTecnico_Nao  \
0                    False                True   
1                     True                True   
2                    False                True   
3                     True               False   
4                    False                True   

   SuporteTecnico_SemServicoDeInternet  SuporteTecnico_Sim  TVaCabo_Nao  \
0                                False               False         True   
1                                False               False         True   
2                                False               False         True   
3                                False                True         True   
4                                False               False         

In [ ]:
Xmaria = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,1]]

In [ ]:
Xmaria

[[0,
  0,
  1,
  1,
  0,
  0,
  39.9,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1]]

In [140]:
X = dados_final.drop('Churn', axis = 1)
y = dados_final['Churn']

In [141]:
from sklearn.preprocessing import StandardScaler

In [142]:
norm = StandardScaler()

X_normalizado = norm.fit_transform(X)
X_normalizado

array([[ 1.03453023, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 , -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
        -0.54480692,  1.88720123]])

In [143]:
X_normalizado[0]

array([ 1.03453023, -0.65401193, -3.05401039,  0.8297975 , -0.43991649,
       -1.27744458, -1.16032292, -0.96332984,  3.05401039, -0.85417615,
        1.38171215, -0.88565976, -0.52592737,  1.00669571, -0.52592737,
       -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
       -0.52592737, -0.72396752,  1.0138687 , -0.52592737, -0.63943864,
        1.2273572 , -0.52592737, -0.79013171,  1.23648892, -0.52592737,
       -0.79607014, -0.56297505,  0.90418382, -0.51424938, -0.52504733,
        1.40641839, -0.54480692, -0.5298852 ])

In [144]:
Xmaria_normalizado = norm.transform(pd.DataFrame(Xmaria, columns = X.columns))
Xmaria_normalizado

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737,  1.00669571, -0.52592737,
        -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322, -0.63943864,
         1.2273572 , -0.52592737, -0.79013171, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 ,  1.94458183, -0.52504733,
        -0.71102597, -0.54480692,  1.88720123]])

In [145]:
import numpy as np

In [146]:
a = Xmaria_normalizado

In [147]:
b = X_normalizado[0]

In [148]:
a - b

array([[-2.00115254,  0.        ,  3.3814487 ,  0.        ,  0.        ,
        -0.04072036,  0.3340212 ,  2.00139589, -3.3814487 ,  0.        ,
        -2.10545189,  2.01476153,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         2.42733059,  0.        , -2.00018971,  2.42733059,  0.        ,
         0.        ,  0.        ,  0.        , -2.0452305 ,  0.        ,
         2.05224086,  0.        , -2.01015362,  2.45883121,  0.        ,
        -2.11744436,  0.        ,  2.41708643]])

In [149]:
np.square(a-b)

array([[4.00461149e+00, 0.00000000e+00, 1.14341953e+01, 0.00000000e+00,
        0.00000000e+00, 1.65814802e-03, 1.11570160e-01, 4.00558550e+00,
        1.14341953e+01, 0.00000000e+00, 4.43292768e+00, 4.05926401e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        5.89193381e+00, 0.00000000e+00, 4.00075888e+00, 5.89193381e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.18296779e+00, 0.00000000e+00, 4.21169253e+00, 0.00000000e+00,
        4.04071758e+00, 6.04585093e+00, 0.00000000e+00, 4.48357062e+00,
        0.00000000e+00, 5.84230682e+00]])

In [150]:
np.sum(np.square(a-b))

84.07574038273466

In [151]:
np.sqrt(84.07574038273466)

9.169282435541762

In [152]:
from sklearn.model_selection import train_test_split

In [153]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X_normalizado, y, test_size=0.3, random_state=123)

In [154]:
from sklearn.neighbors import KNeighborsClassifier

In [155]:
knn = KNeighborsClassifier(metric='euclidean')

In [156]:
knn.fit(X_treino, y_treino)

KNeighborsClassifier(metric='euclidean')

In [157]:
predito_knn = knn.predict(X_teste)

In [158]:
predito_knn

array([1, 0, 0, ..., 0, 0, 0])

In [159]:
np.median(X_treino)

-0.5259273725834717

In [160]:
from sklearn.naive_bayes import BernoulliNB

In [161]:
bnb = BernoulliNB(binarize=0.52)

In [162]:
X_treino

array([[-0.96662231, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 ,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023,  1.5290241 , -3.05401039, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ...,  1.40641839,
        -0.54480692, -0.5298852 ]])

In [163]:
y_treino

1479    0
2377    0
6613    0
6468    0
2668    1
       ..
5218    0
4060    0
1346    1
3454    0
3582    0
Name: Churn, Length: 4930, dtype: int64

In [164]:
bnb.fit(X_treino, y_treino)

BernoulliNB(binarize=0.52)

In [165]:
predito_BNb = bnb.predict(X_teste)

In [166]:
predito_BNb

array([1, 0, 0, ..., 0, 1, 0])

In [167]:
from sklearn.tree import DecisionTreeClassifier

In [168]:
dtc = DecisionTreeClassifier(criterion='entropy', random_state=42)

In [169]:
dtc.fit(X_treino, y_treino)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [170]:
dtc.feature_importances_


array([0.03168742, 0.01862901, 0.00064085, 0.02675693, 0.0208788 ,
       0.2056003 , 0.29546501, 0.0061786 , 0.00273035, 0.00747536,
       0.        , 0.04908356, 0.        , 0.01609395, 0.        ,
       0.00722833, 0.01220706, 0.        , 0.01248286, 0.01138295,
       0.0006673 , 0.0095669 , 0.01841631, 0.        , 0.00650511,
       0.00385849, 0.        , 0.00666929, 0.00517146, 0.        ,
       0.00665371, 0.00473251, 0.15803541, 0.00348686, 0.01414378,
       0.01601964, 0.01064163, 0.01091026])

In [171]:
predito_ArvoreDecisao = dtc.predict(X_teste)

In [172]:
predito_ArvoreDecisao

array([1, 0, 0, ..., 1, 0, 0])

In [173]:
from sklearn.metrics import confusion_matrix

In [174]:
print(confusion_matrix(y_teste, predito_knn))

[[1305  218]
 [ 317  273]]


In [114]:
print(confusion_matrix(y_teste, predito_BNb))

[[1058  465]
 [ 120  470]]


In [115]:
print(confusion_matrix(y_teste, predito_ArvoreDecisao))

[[1249  274]
 [ 290  300]]


In [116]:
from sklearn.metrics import accuracy_score

In [117]:
print(accuracy_score(y_teste, predito_knn))

0.7468054898248935


In [118]:
print(accuracy_score(y_teste, predito_BNb))

0.7231424514907714


In [119]:
print(accuracy_score(y_teste, predito_ArvoreDecisao))

0.7330809275911027


In [120]:
from sklearn.metrics import precision_score

In [121]:
print(precision_score(y_teste, predito_knn))

0.5560081466395111


In [122]:
print(precision_score(y_teste, predito_BNb))

0.5026737967914439


In [123]:
print(precision_score(y_teste, predito_ArvoreDecisao))

0.5226480836236934


In [124]:
from sklearn.metrics import recall_score

In [125]:
print(recall_score(y_teste, predito_knn))

0.46271186440677964


In [126]:
print(recall_score(y_teste, predito_BNb))

0.7966101694915254


In [128]:
print(recall_score(y_teste, predito_ArvoreDecisao))

0.5084745762711864


In [175]:
print('Modelo KNN: ', recall_score(y_teste, predito_knn))
print('Modelo Bernoulli de Naive Bayes: ', recall_score(y_teste, predito_BNb))
print('Modelo Árvore de Decisão: ', recall_score(y_teste, predito_ArvoreDecisao))

Modelo KNN:  0.46271186440677964
Modelo Bernoulli de Naive Bayes:  0.7966101694915254
Modelo Árvore de Decisão:  0.5084745762711864
